### ISSUE TITLE
Confusing layout when a struct only has a single field

### ISSUE THREAD

**Issue by mattwarren** [SergeyTeplyakov/ObjectLayoutInspector#12]
Thanks for the great tool, it's super useful

I just wanted to check something, here's what the `async/await` state machine looks like in .NET Core **2.1**:

![image](https://user-images.githubusercontent.com/157298/49306220-8e6e5780-f4c9-11e8-8ccc-99281d8efede.png)

To me it seems confusing that the fields from `AsyncTaskMethodBuilder <>t__builder` and `TaskAwaiter <>u__1` **aren't** shown in-line in the first diagram. (however they are shown if you look at the types directly, as you can see in the 2nd and 3rd diagrams?). 

Is this done deliberately when a `struct` only contains a single field?

Here's the same state-machine in .NET Core **2.0**, before it was slimmed down, this diagram makes a bit more sense because the fields are shown in-line:

![image](https://user-images.githubusercontent.com/157298/49306184-6ed72f00-f4c9-11e8-937c-469561c79d68.png)

**Comment by SergeyTeplyakov** [comment]
Fixed by #24. Thanks for reporting the issue, @mattwarren and sorry, for some reason I completely missed it:(

**Comment by mattwarren** [comment]
No worries, thanks for the fix and thanks for the great tool!
